import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { ConfigProvider } from "antd";
import Navbar1 from "./ui/Navbar/navbar1";
import { inter } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <ConfigProvider
        theme={{
          token: { colorPrimary: "FF9040" },
          components: {
            Pagination: {
              itemSize: 50,
            },
          },
        }}
      >
        <html lang="en">
          <body className={inter.className}>
            <>
              <Navbar1 />
              {children}
            </>
          </body>
        </html>
      </ConfigProvider>
    </ReactQueryClientProvider>
  );
}
